[package]
name = "day_01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.11", features = ["macros"] }
polars = { version = "0.44.2" }
polars-io = "0.44.2"
regex = "1.11.1"
